[project]
name = "sl-metro-real-time"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "pre-commit>=4.1.0",
    "requests>=2.32.3",
    "ruff>=0.9.6",
]
